public class DefaultFizzBuzz implements IFizzBuzz {
  /**
   * The default FizzBuzz implementation should print out the current number, with these critical exceptions:
   *  - multiples of 3 should print out "Fizz"
   *  - multiples of 5 should print out "Buzz"
   *  - multiples of 15 should print out "FizzBuzz"
   */
  public String call(Integer currentNumber) {
    throw new IllegalArgumentException('Not implemented!');
  }
}
